public class Control_Monad_Writer_Class {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object tell = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("tell");
public static final Object pass = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("pass");
public static final Object listen = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("listen");
public static final Object listens = (java.util.function.Function<Object, Object>) (dictMonadWriter_0) -> { Object Monad1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadWriter_0).get("MonadTell1"))).apply(null /* TODO: PrimUndefined */)).get("Monad1"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad1_1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object pure_3 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad1_1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"); return (java.util.function.Function<Object, Object>) (f_4) -> (java.util.function.Function<Object, Object>) (m_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2).get("bind"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadWriter_0).get("listen"))).apply(m_5)))).apply((java.util.function.Function<Object, Object>) (v_6) -> ((java.util.function.Function<Object, Object>) (pure_3)).apply(new Data_Tuple.Tuple(((Data_Tuple.Tuple) (Object)(v_6)).value0, ((java.util.function.Function<Object, Object>) (f_4)).apply(((Data_Tuple.Tuple) (Object)(v_6)).value1)))); };
public static final Object censor = (java.util.function.Function<Object, Object>) (dictMonadWriter_0) -> { Object Monad1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadWriter_0).get("MonadTell1"))).apply(null /* TODO: PrimUndefined */)).get("Monad1"))).apply(null /* TODO: PrimUndefined */); Object Bind1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad1_1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object pure_3 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad1_1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"); return (java.util.function.Function<Object, Object>) (f_4) -> (java.util.function.Function<Object, Object>) (m_5) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadWriter_0).get("pass"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2).get("bind"))).apply(m_5))).apply((java.util.function.Function<Object, Object>) (a_6) -> ((java.util.function.Function<Object, Object>) (pure_3)).apply(new Data_Tuple.Tuple(a_6, f_4)))); };
}
