public class Control_Monad_Identity_Trans {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object IdentityT = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object monadSTIdentityT = (java.util.function.Function<Object, Object>) (dictMonadST_0) -> dictMonadST_0;
public static final Object traversableIdentityT = (java.util.function.Function<Object, Object>) (dictTraversable_0) -> dictTraversable_0;
public static final Object runIdentityT = (java.util.function.Function<Object, Object>) (v_0) -> v_0;
public static final Object plusIdentityT = (java.util.function.Function<Object, Object>) (dictPlus_0) -> dictPlus_0;
public static final Object newtypeIdentityT = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object monadWriterIdentityT = (java.util.function.Function<Object, Object>) (dictMonadWriter_0) -> dictMonadWriter_0;
public static final Object monadTransIdentityT = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("lift", (java.util.function.Function<Object, Object>) (dictMonad_0) -> (java.util.function.Function<Object, Object>) (x_1) -> x_1);  return __map; } }).get();
public static final Object monadThrowIdentityT = (java.util.function.Function<Object, Object>) (dictMonadThrow_0) -> dictMonadThrow_0;
public static final Object monadTellIdentityT = (java.util.function.Function<Object, Object>) (dictMonadTell_0) -> dictMonadTell_0;
public static final Object monadStateIdentityT = (java.util.function.Function<Object, Object>) (dictMonadState_0) -> dictMonadState_0;
public static final Object monadRecIdentityT = (java.util.function.Function<Object, Object>) (dictMonadRec_0) -> dictMonadRec_0;
public static final Object monadReaderIdentityT = (java.util.function.Function<Object, Object>) (dictMonadReader_0) -> dictMonadReader_0;
public static final Object monadPlusIdentityT = (java.util.function.Function<Object, Object>) (dictMonadPlus_0) -> dictMonadPlus_0;
public static final Object monadIdentityT = (java.util.function.Function<Object, Object>) (dictMonad_0) -> dictMonad_0;
public static final Object monadErrorIdentityT = (java.util.function.Function<Object, Object>) (dictMonadError_0) -> dictMonadError_0;
public static final Object monadEffectIdentityT = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> dictMonadEffect_0;
public static final Object monadContIdentityT = (java.util.function.Function<Object, Object>) (dictMonadCont_0) -> dictMonadCont_0;
public static final Object monadAskIdentityT = (java.util.function.Function<Object, Object>) (dictMonadAsk_0) -> dictMonadAsk_0;
public static final Object mapIdentityT = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1);
public static final Object functorIdentityT = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> dictFunctor_0;
public static final Object foldableIdentityT = (java.util.function.Function<Object, Object>) (dictFoldable_0) -> dictFoldable_0;
public static final Object extendIdentityI = (java.util.function.Function<Object, Object>) (dictExtend_0) -> { Object functorIdentityT1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictExtend_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("extend", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictExtend_0).get("extend"))).apply((java.util.function.Function<Object, Object>) (x_4) -> ((java.util.function.Function<Object, Object>) (f_2)).apply(x_4)))).apply(v_3)); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> functorIdentityT1_1);  return __map; } }).get(); };
public static final Object eqIdentityT = (java.util.function.Function<Object, Object>) (dictEq1_0) -> (java.util.function.Function<Object, Object>) (dictEq_1) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq1_0).get("eq1"))).apply(dictEq_1))).apply(x_2))).apply(y_3));  return __map; } }).get();
public static final Object ordIdentityT = (java.util.function.Function<Object, Object>) (dictOrd1_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("Eq10"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictOrd_2) -> { Object eqIdentityT2_3 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_2).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (x_4) -> (java.util.function.Function<Object, Object>) (y_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq1"))).apply(__local_var_3))).apply(x_4))).apply(y_5));  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (x_4) -> (java.util.function.Function<Object, Object>) (y_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("compare1"))).apply(dictOrd_2))).apply(x_4))).apply(y_5)); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> eqIdentityT2_3);  return __map; } }).get(); }; };
public static final Object eq1IdentityT = (java.util.function.Function<Object, Object>) (dictEq1_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq1", (java.util.function.Function<Object, Object>) (dictEq_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq1_0).get("eq1"))).apply(dictEq_1))).apply(x_2))).apply(y_3));  return __map; } }).get();
public static final Object ord1IdentityT = (java.util.function.Function<Object, Object>) (dictOrd1_0) -> { Object eq1IdentityT1_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("Eq10"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq1", (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq1"))).apply(dictEq_2))).apply(x_3))).apply(y_4));  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_2) -> (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("compare1"))).apply(dictOrd_2))).apply(x_3))).apply(y_4)); __map.put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eq1IdentityT1_1);  return __map; } }).get(); };
public static final Object comonadIdentityT = (java.util.function.Function<Object, Object>) (dictComonad_0) -> { Object extendIdentityI1_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictComonad_0).get("Extend0"))).apply(null /* TODO: PrimUndefined */); Object functorIdentityT1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("extend", (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (v_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("extend"))).apply((java.util.function.Function<Object, Object>) (x_5) -> ((java.util.function.Function<Object, Object>) (f_3)).apply(x_5)))).apply(v_4)); __map.put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> functorIdentityT1_2);  return __map; } }).get(); } }).get(); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("extract", (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictComonad_0).get("extract"))).apply(x_2)); __map.put("Extend0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> extendIdentityI1_1);  return __map; } }).get(); };
public static final Object bindIdentityT = (java.util.function.Function<Object, Object>) (dictBind_0) -> dictBind_0;
public static final Object applyIdentityT = (java.util.function.Function<Object, Object>) (dictApply_0) -> dictApply_0;
public static final Object applicativeIdentityT = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> dictApplicative_0;
public static final Object alternativeIdentityT = (java.util.function.Function<Object, Object>) (dictAlternative_0) -> dictAlternative_0;
public static final Object altIdentityT = (java.util.function.Function<Object, Object>) (dictAlt_0) -> dictAlt_0;
}
