public class Control_Monad_Reader_Class {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object monadAskFun = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("ask", (java.util.function.Function<Object, Object>) (x_0) -> x_0); __map.put("Monad0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad.monadFn);  return __map; } }).get();
public static final Object monadReaderFun = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("local", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (g_1)).apply(((java.util.function.Function<Object, Object>) (f_0)).apply(x_2))); __map.put("MonadAsk0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Monad_Reader_Class.monadAskFun);  return __map; } }).get();
public static final Object local = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("local");
public static final Object ask = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("ask");
public static final Object asks = (java.util.function.Function<Object, Object>) (dictMonadAsk_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadAsk_0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object ask1_2 = ((java.util.LinkedHashMap<String, Object>) dictMonadAsk_0).get("ask"); return (java.util.function.Function<Object, Object>) (f_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(f_3))).apply(ask1_2); };
}
