public class Data_String_CodePoints {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object _codePointAt = FFI_STUB;
    public static Object _codePointAt(Object... args) { return null; }
    public static Object _countPrefix = FFI_STUB;
    public static Object _countPrefix(Object... args) { return null; }
    public static Object _fromCodePointArray = FFI_STUB;
    public static Object _fromCodePointArray(Object... args) { return null; }
    public static Object _singleton = FFI_STUB;
    public static Object _singleton(Object... args) { return null; }
    public static Object _take = FFI_STUB;
    public static Object _take(Object... args) { return null; }
    public static Object _toCodePointArray = FFI_STUB;
    public static Object _toCodePointArray(Object... args) { return null; }
    public static Object _unsafeCodePointAt0 = FFI_STUB;
    public static Object _unsafeCodePointAt0(Object... args) { return null; }

public static final Object showCodePoint = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(CodePoint 0x")) + ((String) (((java.util.function.Function<Object, Object>) (Data_String_Common.toUpper)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Int.toStringAs)).apply(16))).apply(v_0))))))) + ((String) (")"))));  return __map; } }).get();
public static final Object uncons = (java.util.function.Function<Object, Object>) (s_0) -> { Object v_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(s_0); Object cu1_2 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(1))).apply(s_0)); Object cu0_3 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(s_0)); return ( ((Boolean) (java.util.Objects.equals(v_1, 0))) ? new Data_Maybe.Nothing() : ( ((Boolean) (java.util.Objects.equals(v_1, 1))) ? new Data_Maybe.Just((new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("head", ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(s_0))); __map.put("tail", "");  return __map; } }).get()) : ( ((Boolean) ((((Boolean) ((((Boolean) ((((Integer) (55296)) <= ((Integer) (cu0_3))))) && ((Boolean) ((((Integer) (cu0_3)) <= ((Integer) (56319)))))))) && ((Boolean) ((((Boolean) ((((Integer) (56320)) <= ((Integer) (cu1_2))))) && ((Boolean) ((((Integer) (cu1_2)) <= ((Integer) (57343))))))))))) ? new Data_Maybe.Just((new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("head", (((Integer) ((((Integer) ((((Integer) ((((Integer) (cu0_3)) - ((Integer) (55296))))) * ((Integer) (1024))))) + ((Integer) ((((Integer) (cu1_2)) - ((Integer) (56320)))))))) + ((Integer) (65536)))); __map.put("tail", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(2))).apply(s_0));  return __map; } }).get()) : new Data_Maybe.Just((new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("head", cu0_3); __map.put("tail", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(1))).apply(s_0));  return __map; } }).get())))); };
public static final Object unconsButWithTuple = (java.util.function.Function<Object, Object>) (s_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(s_0); return ( ((Boolean) ((__local_var_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(new Data_Tuple.Tuple(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(__local_var_1)).value0).get("head"), ((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(__local_var_1)).value0).get("tail"))) : new Data_Maybe.Nothing()); };
public static final Object toCodePointArrayFallback = (java.util.function.Function<Object, Object>) (s_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable.unfoldrArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(v_1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd))).apply(Data_String_CodePoints.unconsButWithTuple))).apply(s_0);
public static final Object unsafeCodePointAt0Fallback = (java.util.function.Function<Object, Object>) (s_0) -> { Object cu0_1 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(s_0)); return (new java.util.function.Supplier<Object>() { public Object get() {  return ( ((Boolean) ((((Boolean) ((((Boolean) ((((Integer) (55296)) <= ((Integer) (cu0_1))))) && ((Boolean) ((((Integer) (cu0_1)) <= ((Integer) (56319)))))))) && ((Boolean) ((((Integer) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(s_0))) > ((Integer) (1)))))))) ? (new java.util.function.Supplier<Object>() { public Object get() { Object cu1_2 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(1))).apply(s_0)); return ( ((Boolean) ((((Boolean) ((((Integer) (56320)) <= ((Integer) (cu1_2))))) && ((Boolean) ((((Integer) (cu1_2)) <= ((Integer) (57343)))))))) ? (((Integer) ((((Integer) ((((Integer) ((((Integer) (cu0_1)) - ((Integer) (55296))))) * ((Integer) (1024))))) + ((Integer) ((((Integer) (cu1_2)) - ((Integer) (56320)))))))) + ((Integer) (65536))) : cu0_1); } }).get() : cu0_1); } }).get(); };
public static final Object unsafeCodePointAt0 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._unsafeCodePointAt0)).apply(Data_String_CodePoints.unsafeCodePointAt0Fallback);
public static final Object toCodePointArray = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints._toCodePointArray)).apply(Data_String_CodePoints.toCodePointArrayFallback))).apply(Data_String_CodePoints.unsafeCodePointAt0);
public static final Object length = (java.util.function.Function<Object, Object>) (x_0) -> ((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_0)).length;
public static final Object lastIndexOf = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.lastIndexOf)).apply(p_0))).apply(s_1); return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply(((Data_Maybe.Just) (Object)(__local_var_2)).value0))).apply(s_1))).length) : new Data_Maybe.Nothing()); };
public static final Object indexOf = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.indexOf)).apply(p_0))).apply(s_1); return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply(((Data_Maybe.Just) (Object)(__local_var_2)).value0))).apply(s_1))).length) : new Data_Maybe.Nothing()); };
public static final Object fromCharCode = (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.singleton)).apply((new java.util.function.Supplier<Object>() { public Object get() { Object v_1 = ((java.util.function.Function<Object, Object>) (Data_Enum.charToEnum)).apply(x_0); return ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(v_1)).value0 : ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((((Integer) (x_0)) < ((Integer) (((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(Data_Bounded.bottomChar)))))) ? Data_Bounded.bottomChar : Data_Bounded.topChar) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())); } }).get());
public static final Object singletonFallback = (java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) ((((Integer) (v_0)) <= ((Integer) (65535))))) ? ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCharCode)).apply(v_0) : (((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCharCode)).apply((((Integer) ((((Integer) ((((Integer) (v_0)) - ((Integer) (65536))))) / ((Integer) (1024))))) + ((Integer) (55296)))))) + ((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCharCode)).apply((((Integer) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply((((Integer) (v_0)) - ((Integer) (65536)))))).apply(1024))) + ((Integer) (56320))))))));
public static final Object fromCodePointArray = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._fromCodePointArray)).apply(Data_String_CodePoints.singletonFallback);
public static final Object singleton = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._singleton)).apply(Data_String_CodePoints.singletonFallback);
public static final Object takeFallback = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; try { return (new java.util.function.Supplier<Object>() { public Object get() { Object v2_2 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(__final_v1_1); return ( ((Boolean) ((((Integer) (__final_v_0)) < ((Integer) (1))))) ? "" : ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? (((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.singleton)).apply(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(v2_2)).value0).get("head")))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.takeFallback)).apply((((Integer) (__final_v_0)) - ((Integer) (1)))))).apply(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(v2_2)).value0).get("tail"))))) : __final_v1_1)); } }).get(); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; } } } }).get();
public static final Object take = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._take)).apply(Data_String_CodePoints.takeFallback);
public static final Object lastIndexOfprime = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (i_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.lastIndexOfprime)).apply(p_0))).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_1))).apply(s_2))))).apply(s_2); return ( ((Boolean) ((__local_var_3 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply(((Data_Maybe.Just) (Object)(__local_var_3)).value0))).apply(s_2))).length) : new Data_Maybe.Nothing()); };
public static final Object splitAt = (java.util.function.Function<Object, Object>) (i_0) -> (java.util.function.Function<Object, Object>) (s_1) -> { Object before_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_0))).apply(s_1); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("before", before_2); __map.put("after", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(before_2)))).apply(s_1));  return __map; } }).get(); };
public static final Object eqCodePoint = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> java.util.Objects.equals(x_0, y_1));  return __map; } }).get();
public static final Object ordCodePoint = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(x_0))).apply(y_1)); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.eqCodePoint);  return __map; } }).get();
public static final Object drop = (java.util.function.Function<Object, Object>) (n_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(n_0))).apply(s_1))))).apply(s_1);
public static final Object indexOfprime = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (i_1) -> (java.util.function.Function<Object, Object>) (s_2) -> { Object s_prime__3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_1))).apply(s_2))))).apply(s_2); Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.indexOf)).apply(p_0))).apply(s_prime__3); return ( ((Boolean) ((__local_var_4 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just((((Integer) (i_1)) + ((Integer) (((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply(((Data_Maybe.Just) (Object)(__local_var_4)).value0))).apply(s_prime__3))).length)))) : new Data_Maybe.Nothing()); };
public static final Object countTail = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (java.util.function.Function<Object, Object>) (accum_2) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_p_0 = p_0; Object __tco_s_1 = s_1; Object __tco_accum_2 = accum_2; while(true) { final Object __final_p_0 = __tco_p_0; final Object __final_s_1 = __tco_s_1; final Object __final_accum_2 = __tco_accum_2; try { return (new java.util.function.Supplier<Object>() { public Object get() { Object v_3 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(__final_s_1); return ( ((Boolean) ((((Boolean) ((v_3 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (__final_p_0)).apply(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(v_3)).value0).get("head"))))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countTail)).apply(__final_p_0))).apply(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(v_3)).value0).get("tail")))).apply((((Integer) (__final_accum_2)) + ((Integer) (1)))) : __final_accum_2); } }).get(); } catch (TcoLoop __tco_ex) { __tco_p_0 = __tco_ex.args[0]; __tco_s_1 = __tco_ex.args[1]; __tco_accum_2 = __tco_ex.args[2]; } } } }).get();
public static final Object countFallback = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countTail)).apply(p_0))).apply(s_1))).apply(0);
public static final Object countPrefix = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints._countPrefix)).apply(Data_String_CodePoints.countFallback))).apply(Data_String_CodePoints.unsafeCodePointAt0);
public static final Object dropWhile = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countPrefix)).apply(p_0))).apply(s_1)))).apply(s_1))))).apply(s_1);
public static final Object takeWhile = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countPrefix)).apply(p_0))).apply(s_1)))).apply(s_1);
public static final Object codePointFromChar = (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(x_0);
public static final Object codePointAtFallback = (java.util.function.Function<Object, Object>) (n_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco_n_0 = n_0; Object __tco_s_1 = s_1; while(true) { final Object __final_n_0 = __tco_n_0; final Object __final_s_1 = __tco_s_1; try { return (new java.util.function.Supplier<Object>() { public Object get() { Object v_2 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(__final_s_1); return ( ((Boolean) ((v_2 instanceof Data_Maybe.Just))) ? ( ((Boolean) (java.util.Objects.equals(__final_n_0, 0))) ? new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(v_2)).value0).get("head")) : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.codePointAtFallback)).apply((((Integer) (__final_n_0)) - ((Integer) (1)))))).apply(((java.util.LinkedHashMap<String, Object>) ((Data_Maybe.Just) (Object)(v_2)).value0).get("tail"))) : new Data_Maybe.Nothing()); } }).get(); } catch (TcoLoop __tco_ex) { __tco_n_0 = __tco_ex.args[0]; __tco_s_1 = __tco_ex.args[1]; } } } }).get();
public static final Object codePointAt = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((((Integer) (v_0)) < ((Integer) (0))))) ? new Data_Maybe.Nothing() : ( ((Boolean) (java.util.Objects.equals(v_0, 0))) ? ( ((Boolean) (java.util.Objects.equals(v1_1, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.unsafeCodePointAt0)).apply(v1_1))) : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints._codePointAt)).apply(Data_String_CodePoints.codePointAtFallback))).apply(Data_Maybe.Just))).apply(new Data_Maybe.Nothing()))).apply(Data_String_CodePoints.unsafeCodePointAt0))).apply(v_0))).apply(v1_1)));
public static final Object boundedCodePoint = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bottom", 0); __map.put("top", 1114111); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.ordCodePoint);  return __map; } }).get();
public static final Object boundedEnumCodePoint = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cardinality", 1114112); __map.put("fromEnum", (java.util.function.Function<Object, Object>) (v_0) -> v_0); __map.put("toEnum", (java.util.function.Function<Object, Object>) (n_0) -> ( ((Boolean) ((((Boolean) ((((Integer) (n_0)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (n_0)) <= ((Integer) (1114111)))))))) ? new Data_Maybe.Just(n_0) : new Data_Maybe.Nothing())); __map.put("Bounded0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.boundedCodePoint); __map.put("Enum1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.enumCodePoint);  return __map; } }).get();
public static final Object enumCodePoint = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("succ", (java.util.function.Function<Object, Object>) (a_0) -> { Object __local_var_1 = (((Integer) (a_0)) + ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (1114111)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("pred", (java.util.function.Function<Object, Object>) (a_0) -> { Object __local_var_1 = (((Integer) (a_0)) - ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (1114111)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.ordCodePoint);  return __map; } }).get();
}
