public class Data_String_NonEmpty_CaseInsensitive {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object CaseInsensitiveNonEmptyString = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showCaseInsensitiveNonEmptyString = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(CaseInsensitiveNonEmptyString (NonEmptyString.unsafeFromString ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showStringImpl)).apply(v_0)))))) + ((String) ("))"))));  return __map; } }).get();
public static final Object newtypeCaseInsensitiveNonEmptyString = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object eqCaseInsensitiveNonEmptyString = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> java.util.Objects.equals(((java.util.function.Function<Object, Object>) (Data_String_Common.toLower)).apply(v_0), ((java.util.function.Function<Object, Object>) (Data_String_Common.toLower)).apply(v1_1)));  return __map; } }).get();
public static final Object ordCaseInsensitiveNonEmptyString = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordStringImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_String_Common.toLower)).apply(v_0)))).apply(((java.util.function.Function<Object, Object>) (Data_String_Common.toLower)).apply(v1_1))); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_NonEmpty_CaseInsensitive.eqCaseInsensitiveNonEmptyString);  return __map; } }).get();
}
