public class Data_Time_Duration {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Seconds = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object Minutes = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object Milliseconds = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object Hours = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object Days = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object toDuration = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("toDuration");
public static final Object showSeconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Seconds ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showNumberImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showMinutes = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Minutes ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showNumberImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Milliseconds ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showNumberImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showHours = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Hours ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showNumberImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showDays = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Days ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showNumberImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object semigroupSeconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (((Double) (v_0)) + ((Double) (v1_1))));  return __map; } }).get();
public static final Object semigroupMinutes = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (((Double) (v_0)) + ((Double) (v1_1))));  return __map; } }).get();
public static final Object semigroupMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (((Double) (v_0)) + ((Double) (v1_1))));  return __map; } }).get();
public static final Object semigroupHours = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (((Double) (v_0)) + ((Double) (v1_1))));  return __map; } }).get();
public static final Object semigroupDays = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (((Double) (v_0)) + ((Double) (v1_1))));  return __map; } }).get();
public static final Object ordSeconds = Data_Ord.ordNumber;
public static final Object ordMinutes = Data_Ord.ordNumber;
public static final Object ordMilliseconds = Data_Ord.ordNumber;
public static final Object ordHours = Data_Ord.ordNumber;
public static final Object ordDays = Data_Ord.ordNumber;
public static final Object newtypeSeconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object newtypeMinutes = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object newtypeMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object newtypeHours = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object newtypeDays = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */);  return __map; } }).get();
public static final Object monoidSeconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", 0.0); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Duration.semigroupSeconds);  return __map; } }).get();
public static final Object monoidMinutes = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", 0.0); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Duration.semigroupMinutes);  return __map; } }).get();
public static final Object monoidMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", 0.0); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Duration.semigroupMilliseconds);  return __map; } }).get();
public static final Object monoidHours = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", 0.0); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Duration.semigroupHours);  return __map; } }).get();
public static final Object monoidDays = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("mempty", 0.0); __map.put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Duration.semigroupDays);  return __map; } }).get();
public static final Object fromDuration = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("fromDuration");
public static final Object negateDuration = (java.util.function.Function<Object, Object>) (dictDuration_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDuration_0).get("toDuration"))).apply(-(((Double) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDuration_0).get("fromDuration"))).apply(x_1)))));
public static final Object eqSeconds = Data_Eq.eqNumber;
public static final Object eqMinutes = Data_Eq.eqNumber;
public static final Object eqMilliseconds = Data_Eq.eqNumber;
public static final Object eqHours = Data_Eq.eqNumber;
public static final Object eqDays = Data_Eq.eqNumber;
public static final Object durationSeconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("fromDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) * ((Double) (1000.0)))); __map.put("toDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) / ((Double) (1000.0))));  return __map; } }).get();
public static final Object durationMinutes = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("fromDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) * ((Double) (60000.0)))); __map.put("toDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) / ((Double) (60000.0))));  return __map; } }).get();
public static final Object durationMilliseconds = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("fromDuration", (java.util.function.Function<Object, Object>) (x_0) -> x_0); __map.put("toDuration", (java.util.function.Function<Object, Object>) (x_0) -> x_0);  return __map; } }).get();
public static final Object durationHours = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("fromDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) * ((Double) (3600000.0)))); __map.put("toDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) / ((Double) (3600000.0))));  return __map; } }).get();
public static final Object durationDays = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("fromDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) * ((Double) (86400000.0)))); __map.put("toDuration", (java.util.function.Function<Object, Object>) (v_0) -> (((Double) (v_0)) / ((Double) (86400000.0))));  return __map; } }).get();
public static final Object convertDuration = (java.util.function.Function<Object, Object>) (dictDuration_0) -> (java.util.function.Function<Object, Object>) (dictDuration1_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDuration1_1).get("toDuration"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDuration_0).get("fromDuration"))).apply(x_2));
}
