public class Data_List_Partial {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object tail = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_List_Types.Cons))) ? ((Data_List_Types.Cons) (Object)(v_1)).value1 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get());
public static final Object last = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco__dollar___unused_0 = _dollar___unused_0; Object __tco_v_1 = v_1; while(true) { final Object __final__dollar___unused_0 = __tco__dollar___unused_0; final Object __final_v_1 = __tco_v_1; try { return ( ((Boolean) ((__final_v_1 instanceof Data_List_Types.Cons))) ? ( ((Boolean) ((((Data_List_Types.Cons) (Object)(__final_v_1)).value1 instanceof Data_List_Types.Nil))) ? ((Data_List_Types.Cons) (Object)(__final_v_1)).value0 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_List_Partial.last)).apply(null /* TODO: PrimUndefined */))).apply(((Data_List_Types.Cons) (Object)(__final_v_1)).value1)) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); } catch (TcoLoop __tco_ex) { __tco__dollar___unused_0 = __tco_ex.args[0]; __tco_v_1 = __tco_ex.args[1]; } } } }).get();
public static final Object init = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (new java.util.function.Supplier<Object>() { public Object get() { Object __tco__dollar___unused_0 = _dollar___unused_0; Object __tco_v_1 = v_1; while(true) { final Object __final__dollar___unused_0 = __tco__dollar___unused_0; final Object __final_v_1 = __tco_v_1; try { return ( ((Boolean) ((__final_v_1 instanceof Data_List_Types.Cons))) ? ( ((Boolean) ((((Data_List_Types.Cons) (Object)(__final_v_1)).value1 instanceof Data_List_Types.Nil))) ? new Data_List_Types.Nil() : new Data_List_Types.Cons(((Data_List_Types.Cons) (Object)(__final_v_1)).value0, ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_List_Partial.init)).apply(null /* TODO: PrimUndefined */))).apply(((Data_List_Types.Cons) (Object)(__final_v_1)).value1))) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); } catch (TcoLoop __tco_ex) { __tco__dollar___unused_0 = __tco_ex.args[0]; __tco_v_1 = __tco_ex.args[1]; } } } }).get();
public static final Object head = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_List_Types.Cons))) ? ((Data_List_Types.Cons) (Object)(v_1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get());
}
