public class Data_String_NonEmpty_CodePoints {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object snoc = (java.util.function.Function<Object, Object>) (c_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (((String) (s_1)) + ((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.singleton)).apply(c_0))));
public static final Object singleton = (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.singleton)).apply(x_0);
public static final Object takeWhile = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (x_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countPrefix)).apply(f_0))).apply(x_1)))).apply(x_1); return ( ((Boolean) (java.util.Objects.equals(__local_var_2, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_2)); };
public static final Object lastIndexOfprime = (java.util.function.Function<Object, Object>) (pat_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.lastIndexOfprime)).apply(pat_0))).apply(x_1))).apply(v_2);
public static final Object lastIndexOf = (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.lastIndexOf)).apply(x_0))).apply(v_1);
public static final Object indexOfprime = (java.util.function.Function<Object, Object>) (pat_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.indexOfprime)).apply(pat_0))).apply(x_1))).apply(v_2);
public static final Object indexOf = (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.indexOf)).apply(x_0))).apply(v_1);
public static final Object length = (java.util.function.Function<Object, Object>) (x_0) -> ((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_0)).length;
public static final Object splitAt = (java.util.function.Function<Object, Object>) (i_0) -> (java.util.function.Function<Object, Object>) (nes_1) -> { Object v_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.splitAt)).apply(i_0))).apply(nes_1); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("before", ( ((Boolean) (java.util.Objects.equals(((java.util.LinkedHashMap<String, Object>) v_2).get("before"), ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) v_2).get("before")))); __map.put("after", ( ((Boolean) (java.util.Objects.equals(((java.util.LinkedHashMap<String, Object>) v_2).get("after"), ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) v_2).get("after"))));  return __map; } }).get(); };
public static final Object take = (java.util.function.Function<Object, Object>) (i_0) -> (java.util.function.Function<Object, Object>) (nes_1) -> ( ((Boolean) ((((Integer) (i_0)) < ((Integer) (1))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_0))).apply(nes_1)));
public static final Object toCodePointArray = (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_0);
public static final Object toNonEmptyCodePointArray = (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_0); return ( ((Boolean) ((((Integer) (((Object[]) __local_var_1).length)) > ((Integer) (0))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); } }).get(); return ( ((Boolean) ((__local_var_1 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(__local_var_1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); };
public static final Object uncons = (java.util.function.Function<Object, Object>) (nes_0) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("head", (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.codePointAt)).apply(0))).apply(nes_0); return ( ((Boolean) ((__local_var_1 instanceof Data_Maybe.Just))) ? ((Data_Maybe.Just) (Object)(__local_var_1)).value0 : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); } }).get()); __map.put("tail", (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(1))).apply(nes_0))))).apply(nes_0); return ( ((Boolean) (java.util.Objects.equals(__local_var_1, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_1)); } }).get());  return __map; } }).get();
public static final Object fromFoldable1 = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable1_0).get("foldMap1"))).apply(Data_Semigroup.semigroupString))).apply(Data_String_NonEmpty_CodePoints.singleton);
public static final Object fromCodePointArray = (java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) (java.util.Objects.equals(((Object[]) v_0).length, 0))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCodePointArray)).apply(v_0)));
public static final Object fromNonEmptyCodePointArray = (java.util.function.Function<Object, Object>) (x_0) -> ( ((Boolean) (java.util.Objects.equals(((Object[]) x_0).length, 0))) ? (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get() : ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCodePointArray)).apply(x_0));
public static final Object dropWhile = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (x_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.dropWhile)).apply(f_0))).apply(x_1); return ( ((Boolean) (java.util.Objects.equals(__local_var_2, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_2)); };
public static final Object drop = (java.util.function.Function<Object, Object>) (i_0) -> (java.util.function.Function<Object, Object>) (nes_1) -> ( ((Boolean) ((((Integer) (i_0)) >= ((Integer) (((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(nes_1)).length))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_0))).apply(nes_1))))).apply(nes_1)));
public static final Object countPrefix = (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countPrefix)).apply(x_0); return (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(v_2); };
public static final Object cons = (java.util.function.Function<Object, Object>) (c_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.singleton)).apply(c_0))) + ((String) (s_1)));
public static final Object codePointAt = (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.codePointAt)).apply(x_0))).apply(v_1);
}
