public class Data_Time_Component {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object showSecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Second ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showMinute = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Minute ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Millisecond ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object showHour = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(Hour ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(v_0)))))) + ((String) (")"))));  return __map; } }).get();
public static final Object ordSecond = Data_Ord.ordInt;
public static final Object ordMinute = Data_Ord.ordInt;
public static final Object ordMillisecond = Data_Ord.ordInt;
public static final Object ordHour = Data_Ord.ordInt;
public static final Object eqSecond = Data_Eq.eqInt;
public static final Object eqMinute = Data_Eq.eqInt;
public static final Object eqMillisecond = Data_Eq.eqInt;
public static final Object eqHour = Data_Eq.eqInt;
public static final Object boundedSecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bottom", 0); __map.put("top", 59); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedMinute = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bottom", 0); __map.put("top", 59); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bottom", 0); __map.put("top", 999); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedHour = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("bottom", 0); __map.put("top", 23); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedEnumSecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cardinality", 60); __map.put("toEnum", (java.util.function.Function<Object, Object>) (n_0) -> ( ((Boolean) ((((Boolean) ((((Integer) (n_0)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (n_0)) <= ((Integer) (59)))))))) ? new Data_Maybe.Just(n_0) : new Data_Maybe.Nothing())); __map.put("fromEnum", (java.util.function.Function<Object, Object>) (v_0) -> v_0); __map.put("Bounded0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.boundedSecond); __map.put("Enum1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.enumSecond);  return __map; } }).get();
public static final Object enumSecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("succ", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) + ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (59)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("pred", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) - ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (59)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedEnumMinute = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cardinality", 60); __map.put("toEnum", (java.util.function.Function<Object, Object>) (n_0) -> ( ((Boolean) ((((Boolean) ((((Integer) (n_0)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (n_0)) <= ((Integer) (59)))))))) ? new Data_Maybe.Just(n_0) : new Data_Maybe.Nothing())); __map.put("fromEnum", (java.util.function.Function<Object, Object>) (v_0) -> v_0); __map.put("Bounded0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.boundedMinute); __map.put("Enum1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.enumMinute);  return __map; } }).get();
public static final Object enumMinute = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("succ", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) + ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (59)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("pred", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) - ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (59)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedEnumMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cardinality", 1000); __map.put("toEnum", (java.util.function.Function<Object, Object>) (n_0) -> ( ((Boolean) ((((Boolean) ((((Integer) (n_0)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (n_0)) <= ((Integer) (999)))))))) ? new Data_Maybe.Just(n_0) : new Data_Maybe.Nothing())); __map.put("fromEnum", (java.util.function.Function<Object, Object>) (v_0) -> v_0); __map.put("Bounded0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.boundedMillisecond); __map.put("Enum1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.enumMillisecond);  return __map; } }).get();
public static final Object enumMillisecond = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("succ", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) + ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (999)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("pred", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) - ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (999)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
public static final Object boundedEnumHour = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("cardinality", 24); __map.put("toEnum", (java.util.function.Function<Object, Object>) (n_0) -> ( ((Boolean) ((((Boolean) ((((Integer) (n_0)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (n_0)) <= ((Integer) (23)))))))) ? new Data_Maybe.Just(n_0) : new Data_Maybe.Nothing())); __map.put("fromEnum", (java.util.function.Function<Object, Object>) (v_0) -> v_0); __map.put("Bounded0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.boundedHour); __map.put("Enum1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Time_Component.enumHour);  return __map; } }).get();
public static final Object enumHour = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("succ", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) + ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (23)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("pred", (java.util.function.Function<Object, Object>) (x_0) -> { Object __local_var_1 = (((Integer) (x_0)) - ((Integer) (1))); return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (23)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); }); __map.put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ord.ordInt);  return __map; } }).get();
}
