public class Foreign_Keys {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object unsafeKeys = FFI_STUB;
    public static Object unsafeKeys(Object... args) { return null; }

public static final Object keys = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object fail_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"); return (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(new Data_Either.Left(x_2)); } }).get(); return (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(new Data_NonEmpty.NonEmpty(x_2, new Data_List_Types.Nil())); } }).get(); Object pure_2 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"); return (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (__local_var_2)).apply(new Data_Either.Right(x_3)); } }).get(); return (java.util.function.Function<Object, Object>) (value_3) -> ( ((Boolean) (((java.util.function.Function<Object, Object>) (Foreign.isNull)).apply(value_3))) ? ((java.util.function.Function<Object, Object>) (fail_1)).apply(new Foreign.TypeMismatch("object", "null")) : ( ((Boolean) (((java.util.function.Function<Object, Object>) (Foreign.isUndefined)).apply(value_3))) ? ((java.util.function.Function<Object, Object>) (fail_1)).apply(new Foreign.TypeMismatch("object", "undefined")) : ( ((Boolean) (java.util.Objects.equals(((java.util.function.Function<Object, Object>) (Foreign.typeOf)).apply(value_3), "object"))) ? ((java.util.function.Function<Object, Object>) (pure_2)).apply(((java.util.function.Function<Object, Object>) (Foreign_Keys.unsafeKeys)).apply(value_3)) : ((java.util.function.Function<Object, Object>) (fail_1)).apply(new Foreign.TypeMismatch("object", ((java.util.function.Function<Object, Object>) (Foreign.typeOf)).apply(value_3)))))); };
}
